<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Kawazu" Version="1.1.4" GeneratePathProperty="true" />
  </ItemGroup>

  <ItemGroup>
    <None Include="$(PkgKawazu)\contentFiles\any\net5.0\*" Link="IpaDic\%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" Visible="false" />
  </ItemGroup>

</Project>
